version: '3'
services:
  mongodb:
    image: mongo:4.0-xenial
    container_name: my_mongodb_for_BookStoreManagement
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password